import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" bg-blue-300 p-[1rem]">
          <p>header</p>
        </header>
        {children}
        <footer className=" bg-blue-950 p-[1rem]">
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
